before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
main:
  tags:
    - shell
  script:
    - docker build -t ostrich .
    - docker run --rm --entrypoint /opt/patchstore/build/tpfpatch_store_test ostrich